name: Build and Dockerize FastAPI App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-app:
    name: Build FastAPI App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic app build check
        run: |
          python -m py_compile app/main.py

      # Optional: Save build artifacts
      - name: Upload source code artifact
        uses: actions/upload-artifact@v3
        with:
          name: fastapi-source
          path: .
  
  dockerize-and-push:
    name: Dockerize & Push to DockerHub
    runs-on: ubuntu-latest
    needs: build-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-cicd:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
